

export const stopwordsFr = [
  "a", "afin", "ai", "aie", "aient", "aies", "aille", "aillent", "ailles", "ainsi", "ait", "allaient", "allais", "allait", "allas", "allez", "alliez", "allions", "allons", "alors", "après", "assez", "au", "aucun", "aucune", "aujourd", "aupres", "auquel", "aura", "aurai", "auraient", "aurais", "aurait", "auras", "aurez", "auriez", "aurions", "aurons", "auront", "aussi", "autre", "autres", "aux", "auxquelles", "auxquels", "avaient", "avais", "avait", "avant", "avec", "avez", "aviez", "avions", "avoir", "avons", "c", "car", "ce", "cedi", "cela", "celle", "celles", "celui", "celui-ci", "cent", "cependant", "certain", "certaine", "certaines", "certains", "ces", "cet", "cette", "ceux", "ceux-ci", "chacun", "chaque", "chez", "ci", "comme", "comment", "d", "da", "dans", "de", "debout", "deja", "delà", "depuis", "des", "desormais", "desquelles", "desquels", "dessous", "dessus", "deux", "deuxieme", "deuxiemement", "devers", "doit", "doivent", "donc", "dont", "du", "duquel", "elle", "elles", "en", "encore", "enfin", "entre", "envers", "environ", "est", "et", "etaient", "etais", "etait", "etant", "ete", "etes", "etre", "eu", "eue", "eues", "euh", "eux", "fait", "faites", "fois", "font", "hors", "ici", "il", "ils", "j", "je", "jusqu", "la", "le", "les", "leur", "leurs", "lors", "lorsque", "lui", "ma", "mais", "me", "meme", "memes", "mes", "moi", "moi-meme", "mon", "moyennant", "ne", "ni", "nos", "notre", "nous", "nouveau", "nulle", "on", "ont", "ou", "où", "par", "parce", "parmi", "pas", "pendant", "peu", "peut", "peuvent", "peux", "plus", "plusieurs", "pour", "pourquoi", "qu", "quand", "que", "quel", "quelle", "quelles", "quelqu", "quelque", "quelques", "quels", "qui", "quiconque", "sa", "sans", "se", "selon", "ses", "si", "sien", "son", "sont", "sous", "suivant", "sur", "ta", "tandis", "te", "tes", "toi", "ton", "tous", "tout", "toute", "toutes", "trois", "trop", "tu", "voici", "voilà", "vos", "votre", "vous", "vu",
  
  "cc", "coucou", "bjr", "bonjour", "slt", "salut", "hello", "yo", "ok", "okay", "dacc", "daccord", "lol", "mdr", "ptdr", "stp", "svp", "sil", "plait", "merci",
  
  "prix", "combien", "coute", "cout", "couter", "tarif", "ca", "coute", "disponible", "dispo", "stock", "rupture", "reste", "restant", "avoir", "vendre", "vendez", "vendu", "acheter", "achete", "commander", "commande", "prendre", "prends", "montrez", "voir", "montre", "photo", "images", "image", "catalogue", "envoyer", "envoie", "livraison", "expedition",
  
  "tres", "beaucoup", "peu", "bien", "mal", "vite", "lentement", "vite", "bas", "haut", "chez", "vers", "ici", "la"
]

